/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VtnCRUD extends javax.swing.JFrame
{

     /**
      * Creates new form VtnCRUD
      */
     public VtnCRUD()
     {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jpnLateral = new javax.swing.JPanel();
          PrincipalBtn = new javax.swing.JButton();
          Fondo = new javax.swing.JPanel();
          Principal = new javax.swing.JPanel();
          Paciente = new javax.swing.JPanel();
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          VigenciaTxt = new javax.swing.JTextField();
          NPaciente = new javax.swing.JTextField();
          jComboBox1 = new javax.swing.JComboBox<>();
          RegistrarBtn = new javax.swing.JButton();
          jLabel13 = new javax.swing.JLabel();
          CveTxt = new javax.swing.JTextField();
          RegistrarBtn1 = new javax.swing.JButton();
          Status = new javax.swing.JComboBox<>();
          Dependencia = new javax.swing.JPanel();
          jLabel5 = new javax.swing.JLabel();
          NPaciente1 = new javax.swing.JTextField();
          jLabel7 = new javax.swing.JLabel();
          jComboBox2 = new javax.swing.JComboBox<>();
          RegistrarDepBtn = new javax.swing.JButton();
          Hospital = new javax.swing.JPanel();
          jLabel6 = new javax.swing.JLabel();
          NHospital = new javax.swing.JTextField();
          jLabel8 = new javax.swing.JLabel();
          NHospital1 = new javax.swing.JTextField();
          NHospital2 = new javax.swing.JTextField();
          jLabel14 = new javax.swing.JLabel();
          RegistrarHospBtn = new javax.swing.JButton();
          Especialidad = new javax.swing.JPanel();
          EspecialidadTxt = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          RegistrarEspBtn = new javax.swing.JButton();
          jLabel4 = new javax.swing.JLabel();
          jLabel15 = new javax.swing.JLabel();
          EspecialidadTxt1 = new javax.swing.JTextField();
          EspecialidadTxt2 = new javax.swing.JTextField();
          DependenciaBtn = new javax.swing.JButton();
          DependenciaBtn1 = new javax.swing.JButton();
          EspecialidadesBtn = new javax.swing.JButton();
          PacientesBtn = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jpnLateral.setBackground(new java.awt.Color(102, 204, 255));

          PrincipalBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          PrincipalBtn.setText("Principal");
          PrincipalBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          PrincipalBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    PrincipalBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jpnLateralLayout = new javax.swing.GroupLayout(jpnLateral);
          jpnLateral.setLayout(jpnLateralLayout);
          jpnLateralLayout.setHorizontalGroup(
               jpnLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLateralLayout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(PrincipalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );
          jpnLateralLayout.setVerticalGroup(
               jpnLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jpnLateralLayout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(PrincipalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE))
          );

          Fondo.setBackground(new java.awt.Color(153, 153, 255));
          Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          Principal.setBackground(new java.awt.Color(255, 255, 255));
          Principal.setLayout(new java.awt.CardLayout());

          Paciente.setBackground(new java.awt.Color(255, 255, 255));

          jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel9.setText("Nombre:");

          jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel10.setText("Estatus:");

          jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel11.setText("Vigencia:");

          jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel12.setText("Sexo:");

          VigenciaTxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          VigenciaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          VigenciaTxt.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    VigenciaTxtKeyTyped(evt);
               }
          });

          NPaciente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NPaciente.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NPacienteKeyTyped(evt);
               }
          });

          jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Masculino", "Femenino", " " }));
          jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          RegistrarBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarBtn.setText("Registrar");
          RegistrarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarBtnActionPerformed(evt);
               }
          });

          jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel13.setText("CVE:");

          CveTxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          CveTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          CveTxt.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    CveTxtKeyTyped(evt);
               }
          });

          RegistrarBtn1.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarBtn1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarBtn1.setText("Registrar");
          RegistrarBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarBtn1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarBtn1ActionPerformed(evt);
               }
          });

          Status.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Activo", "Inactivo", " " }));
          Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          javax.swing.GroupLayout PacienteLayout = new javax.swing.GroupLayout(Paciente);
          Paciente.setLayout(PacienteLayout);
          PacienteLayout.setHorizontalGroup(
               PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(PacienteLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(RegistrarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap())
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PacienteLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18))
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addComponent(NPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148)
                                        .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel13)
                                             .addComponent(jLabel11))))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(VigenciaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                             .addComponent(CveTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(120, 120, 120))
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
          );
          PacienteLayout.setVerticalGroup(
               PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(PacienteLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel9)
                         .addComponent(NPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel10)
                         .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel11)
                                   .addComponent(jLabel12)
                                   .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel13))
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addComponent(VigenciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(CveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(32, 32, 32)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(RegistrarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(114, Short.MAX_VALUE))
          );

          Principal.add(Paciente, "card2");

          Dependencia.setBackground(new java.awt.Color(255, 255, 255));

          jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel5.setText("Dependencia:");

          NPaciente1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NPaciente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NPaciente1.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NPaciente1KeyTyped(evt);
               }
          });

          jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel7.setText("Tipo: ");

          jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Federal", "Estatal", "Municipal", " ", " " }));
          jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          RegistrarDepBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarDepBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarDepBtn.setText("Registrar");
          RegistrarDepBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarDepBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarDepBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout DependenciaLayout = new javax.swing.GroupLayout(Dependencia);
          Dependencia.setLayout(DependenciaLayout);
          DependenciaLayout.setHorizontalGroup(
               DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(DependenciaLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(RegistrarDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(DependenciaLayout.createSequentialGroup()
                              .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel5)
                                   .addComponent(jLabel7))
                              .addGap(18, 18, 18)
                              .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(NPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(296, Short.MAX_VALUE))
          );
          DependenciaLayout.setVerticalGroup(
               DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(DependenciaLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(NPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(55, 55, 55)
                    .addComponent(RegistrarDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(129, Short.MAX_VALUE))
          );

          Principal.add(Dependencia, "card5");

          Hospital.setBackground(new java.awt.Color(255, 255, 255));

          jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel6.setText("Cve:");

          NHospital.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NHospital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NHospital.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NHospitalKeyTyped(evt);
               }
          });

          jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel8.setText("Dirección:");

          NHospital1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NHospital1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NHospital1.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NHospital1KeyTyped(evt);
               }
          });

          NHospital2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NHospital2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NHospital2.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NHospital2KeyTyped(evt);
               }
          });

          jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel14.setText("Nivel:");

          RegistrarHospBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarHospBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarHospBtn.setText("Registrar");
          RegistrarHospBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarHospBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarHospBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout HospitalLayout = new javax.swing.GroupLayout(Hospital);
          Hospital.setLayout(HospitalLayout);
          HospitalLayout.setHorizontalGroup(
               HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(HospitalLayout.createSequentialGroup()
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(HospitalLayout.createSequentialGroup()
                              .addGap(29, 29, 29)
                              .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel14)
                                   .addComponent(jLabel6))
                              .addGap(31, 31, 31))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospitalLayout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(RegistrarHospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel8))
                              .addGap(18, 18, 18)))
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(NHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(NHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(NHospital2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(357, Short.MAX_VALUE))
          );
          HospitalLayout.setVerticalGroup(
               HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(HospitalLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel6)
                         .addComponent(NHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(NHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(NHospital2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel8))
                    .addGap(57, 57, 57)
                    .addComponent(RegistrarHospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE))
          );

          Principal.add(Hospital, "card4");

          Especialidad.setBackground(new java.awt.Color(255, 255, 255));

          EspecialidadTxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          EspecialidadTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          EspecialidadTxt.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    EspecialidadTxtKeyTyped(evt);
               }
          });

          jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel3.setText("Cve:");

          RegistrarEspBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarEspBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarEspBtn.setText("Registrar");
          RegistrarEspBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarEspBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarEspBtnActionPerformed(evt);
               }
          });

          jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel4.setText("Número de medicos: ");

          jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel15.setText("Número de camas: ");

          EspecialidadTxt1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          EspecialidadTxt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          EspecialidadTxt1.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    EspecialidadTxt1KeyTyped(evt);
               }
          });

          EspecialidadTxt2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          EspecialidadTxt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          EspecialidadTxt2.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    EspecialidadTxt2KeyTyped(evt);
               }
          });

          javax.swing.GroupLayout EspecialidadLayout = new javax.swing.GroupLayout(Especialidad);
          Especialidad.setLayout(EspecialidadLayout);
          EspecialidadLayout.setHorizontalGroup(
               EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(EspecialidadLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addComponent(RegistrarEspBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap())
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel15)
                                   .addComponent(jLabel3))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(EspecialidadLayout.createSequentialGroup()
                                        .addComponent(EspecialidadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                        .addGap(143, 143, 143))
                                   .addGroup(EspecialidadLayout.createSequentialGroup()
                                        .addComponent(EspecialidadTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                        .addGap(143, 143, 143))
                                   .addGroup(EspecialidadLayout.createSequentialGroup()
                                        .addComponent(EspecialidadTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                        .addGap(152, 152, 152))))))
          );
          EspecialidadLayout.setVerticalGroup(
               EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(EspecialidadLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(EspecialidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel15)
                         .addComponent(EspecialidadTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(EspecialidadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(70, 70, 70)
                    .addComponent(RegistrarEspBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(94, 94, 94))
          );

          Principal.add(Especialidad, "card3");

          Fondo.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 750, 380));

          DependenciaBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          DependenciaBtn.setText("Dependencias");
          DependenciaBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          DependenciaBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    DependenciaBtnActionPerformed(evt);
               }
          });
          Fondo.add(DependenciaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 50));

          DependenciaBtn1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          DependenciaBtn1.setText("Hospitales");
          DependenciaBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          DependenciaBtn1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    DependenciaBtn1ActionPerformed(evt);
               }
          });
          Fondo.add(DependenciaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 50));

          EspecialidadesBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          EspecialidadesBtn.setText("Especialidades");
          EspecialidadesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          EspecialidadesBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    EspecialidadesBtnActionPerformed(evt);
               }
          });
          Fondo.add(EspecialidadesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 160, 50));

          PacientesBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          PacientesBtn.setText("Pacientes");
          PacientesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          PacientesBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    PacientesBtnActionPerformed(evt);
               }
          });
          Fondo.add(PacientesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 140, 50));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addComponent(jpnLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(0, 749, Short.MAX_VALUE)))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnLateral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void RegistrarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarBtnActionPerformed
/*          
                    try
          {
               String nombre = NPaciente.getText();
               int numero = Integer.parseInt(Numero.getText());
               int prioridad = Integer.parseInt(Prioridad.getText());
               int zona = Integer.parseInt(Zona.getText());

               if (prioridad < 1 || prioridad > 10)
               {
                    JOptionPane.showMessageDialog(
                            this,
                            "La prioridad debe estar entre 1 y 10.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
               }

               if (zona < 1 || zona > 10)
               {
                    JOptionPane.showMessageDialog(
                            this,
                            "La zona debe estar entre 1 y 10.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
               }

               Paciente nuevoPaciente = new Paciente(nombre, numero, nombre, prioridad, zona);

               Nodo<Paciente> nuevoNodo = new Nodo<>(nuevoPaciente);

               Lista<Nodo<Paciente>> lista = new Lista<>();
               lista.insertar(nuevoNodo);

               Archivos.guardar(lista);
               CtrlInterfaz.limpia(Nombre);
               CtrlInterfaz.limpia(Numero);
               CtrlInterfaz.limpia(Prioridad);
               CtrlInterfaz.limpia(Zona);
               JOptionPane.showMessageDialog(
                       this,
                       "Los datos se guardaron correctamente.",
                       "Éxito",
                       JOptionPane.INFORMATION_MESSAGE
               );
          } catch (NumberFormatException e)
          {
               JOptionPane.showMessageDialog(
                       this,
                       "Error: Asegúrate de que los datos ingresados sean válidos.",
                       "Error",
                       JOptionPane.ERROR_MESSAGE
               );
          } catch (Exception e)
          {
               JOptionPane.showMessageDialog(
                       this,
                       "Error: No se pudieron guardar los datos.",
                       "Error",
                       JOptionPane.ERROR_MESSAGE
               );
          }
*/

     }//GEN-LAST:event_RegistrarBtnActionPerformed

     private void NPacienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NPacienteKeyTyped
     {//GEN-HEADEREND:event_NPacienteKeyTyped

          Validaciones.validaAlfabeticos(evt);

     }//GEN-LAST:event_NPacienteKeyTyped

     private void VigenciaTxtKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_VigenciaTxtKeyTyped
     {//GEN-HEADEREND:event_VigenciaTxtKeyTyped
        
          //Validaciones.validaEntero(evt, 8, Status.getText());
          CtrlInterfaz.habilita(rootPaneCheckingEnabled, RegistrarBtn);     }//GEN-LAST:event_VigenciaTxtKeyTyped

     private void EspecialidadTxtKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_EspecialidadTxtKeyTyped
     {//GEN-HEADEREND:event_EspecialidadTxtKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_EspecialidadTxtKeyTyped

     private void DependenciaBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DependenciaBtnActionPerformed
     {//GEN-HEADEREND:event_DependenciaBtnActionPerformed
          Principal.removeAll();
          Principal.add(Dependencia);
          Principal.repaint();
          Principal.revalidate();
     }//GEN-LAST:event_DependenciaBtnActionPerformed

     private void DependenciaBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DependenciaBtn1ActionPerformed
     {//GEN-HEADEREND:event_DependenciaBtn1ActionPerformed
          Principal.removeAll();
          Principal.add(Hospital);
          Principal.repaint();
     }//GEN-LAST:event_DependenciaBtn1ActionPerformed

     private void EspecialidadesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EspecialidadesBtnActionPerformed
     {//GEN-HEADEREND:event_EspecialidadesBtnActionPerformed
          Principal.removeAll();
          Principal.add(Especialidad);
          Principal.repaint();
     }//GEN-LAST:event_EspecialidadesBtnActionPerformed

     private void PacientesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PacientesBtnActionPerformed
     {//GEN-HEADEREND:event_PacientesBtnActionPerformed
          Principal.removeAll();
          Principal.add(Paciente);
          Principal.repaint();
     }//GEN-LAST:event_PacientesBtnActionPerformed

     private void CveTxtKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveTxtKeyTyped
     {//GEN-HEADEREND:event_CveTxtKeyTyped
          Validaciones.validaAlfanumerico(evt, 4, CveTxt.getText());
          CtrlInterfaz.habilita(rootPaneCheckingEnabled, RegistrarBtn);
          
     }//GEN-LAST:event_CveTxtKeyTyped

     private void RegistrarEspBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarEspBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarEspBtnActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_RegistrarEspBtnActionPerformed

     private void PrincipalBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PrincipalBtnActionPerformed
     {//GEN-HEADEREND:event_PrincipalBtnActionPerformed
          VtnGeneral segundoFrame = new VtnGeneral();
          segundoFrame.setVisible(true);
          this.dispose();
     }//GEN-LAST:event_PrincipalBtnActionPerformed

     private void NPaciente1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NPaciente1KeyTyped
     {//GEN-HEADEREND:event_NPaciente1KeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_NPaciente1KeyTyped

     private void RegistrarDepBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarDepBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarDepBtnActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_RegistrarDepBtnActionPerformed

     private void NHospitalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NHospitalKeyTyped
     {//GEN-HEADEREND:event_NHospitalKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_NHospitalKeyTyped

     private void NHospital1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NHospital1KeyTyped
     {//GEN-HEADEREND:event_NHospital1KeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_NHospital1KeyTyped

     private void NHospital2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NHospital2KeyTyped
     {//GEN-HEADEREND:event_NHospital2KeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_NHospital2KeyTyped

     private void RegistrarHospBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarHospBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarHospBtnActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_RegistrarHospBtnActionPerformed

     private void EspecialidadTxt1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_EspecialidadTxt1KeyTyped
     {//GEN-HEADEREND:event_EspecialidadTxt1KeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_EspecialidadTxt1KeyTyped

     private void EspecialidadTxt2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_EspecialidadTxt2KeyTyped
     {//GEN-HEADEREND:event_EspecialidadTxt2KeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_EspecialidadTxt2KeyTyped

     private void RegistrarBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarBtn1ActionPerformed
     {//GEN-HEADEREND:event_RegistrarBtn1ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_RegistrarBtn1ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Nimbus".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(VtnCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(VtnCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(VtnCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(VtnCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    new VtnCRUD().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTextField CveTxt;
     private javax.swing.JPanel Dependencia;
     private javax.swing.JButton DependenciaBtn;
     private javax.swing.JButton DependenciaBtn1;
     private javax.swing.JPanel Especialidad;
     private javax.swing.JTextField EspecialidadTxt;
     private javax.swing.JTextField EspecialidadTxt1;
     private javax.swing.JTextField EspecialidadTxt2;
     private javax.swing.JButton EspecialidadesBtn;
     private javax.swing.JPanel Fondo;
     private javax.swing.JPanel Hospital;
     private javax.swing.JTextField NHospital;
     private javax.swing.JTextField NHospital1;
     private javax.swing.JTextField NHospital2;
     private javax.swing.JTextField NPaciente;
     private javax.swing.JTextField NPaciente1;
     private javax.swing.JPanel Paciente;
     private javax.swing.JButton PacientesBtn;
     private javax.swing.JPanel Principal;
     private javax.swing.JButton PrincipalBtn;
     private javax.swing.JButton RegistrarBtn;
     private javax.swing.JButton RegistrarBtn1;
     private javax.swing.JButton RegistrarDepBtn;
     private javax.swing.JButton RegistrarEspBtn;
     private javax.swing.JButton RegistrarHospBtn;
     private javax.swing.JComboBox<String> Status;
     private javax.swing.JTextField VigenciaTxt;
     private javax.swing.JComboBox<String> jComboBox1;
     private javax.swing.JComboBox<String> jComboBox2;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jpnLateral;
     // End of variables declaration//GEN-END:variables
}
