package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import edd_hospital_.modelo.Dependencia;
import edd_hospital_.multi_lista.NodoML;
import javax.swing.JButton;

public class vtnDependencia extends javax.swing.JFrame
{

     private NodoML nodoDependencia;

     /**
      * Creates new form vtnDependencia
      */
     public vtnDependencia()
     {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          Fondo = new javax.swing.JPanel();
          jPanel1 = new javax.swing.JPanel();
          RegresarBtn = new javax.swing.JButton();
          Dependencia = new javax.swing.JPanel();
          jLabel5 = new javax.swing.JLabel();
          CveDepen = new javax.swing.JTextField();
          jLabel7 = new javax.swing.JLabel();
          OpcDepen = new javax.swing.JComboBox<>();
          RegistrarDepBtn = new javax.swing.JButton();
          Cancelar = new javax.swing.JButton();
          jLabel8 = new javax.swing.JLabel();
          DepenTxt = new javax.swing.JTextField();
          jLabel6 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setMinimumSize(new java.awt.Dimension(420, 285));
          setResizable(false);

          Fondo.setBackground(new java.awt.Color(153, 153, 255));
          Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(102, 204, 255));

          RegresarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
          RegresarBtn.setText("Regresar");
          RegresarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegresarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegresarBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 152, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(15, 15, 15)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(15, Short.MAX_VALUE)))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 450, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(204, 204, 204)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(205, Short.MAX_VALUE)))
          );

          Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

          Dependencia.setBackground(new java.awt.Color(255, 255, 255));

          jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel5.setText("Cve Dependencia:");

          CveDepen.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          CveDepen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          CveDepen.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    CveDepenKeyTyped(evt);
               }
          });

          jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel7.setText("Tipo: ");

          OpcDepen.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          OpcDepen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Federal", "Estatal", "Municipal", " ", " " }));
          OpcDepen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          RegistrarDepBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarDepBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarDepBtn.setText("Registrar");
          RegistrarDepBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarDepBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarDepBtnActionPerformed(evt);
               }
          });

          Cancelar.setBackground(new java.awt.Color(153, 204, 255));
          Cancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          Cancelar.setText("Cancelar");
          Cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          Cancelar.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CancelarActionPerformed(evt);
               }
          });

          jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel8.setText("Dependencia:");

          DepenTxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          DepenTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          DepenTxt.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    DepenTxtKeyTyped(evt);
               }
          });

          javax.swing.GroupLayout DependenciaLayout = new javax.swing.GroupLayout(Dependencia);
          Dependencia.setLayout(DependenciaLayout);
          DependenciaLayout.setHorizontalGroup(
               DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(DependenciaLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel8)
                         .addGroup(DependenciaLayout.createSequentialGroup()
                              .addComponent(RegistrarDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(139, 139, 139)
                              .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(DependenciaLayout.createSequentialGroup()
                              .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel5)
                                   .addComponent(jLabel7))
                              .addGap(18, 18, 18)
                              .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(CveDepen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(OpcDepen, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(304, Short.MAX_VALUE))
               .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DependenciaLayout.createSequentialGroup()
                         .addGap(240, 240, 240)
                         .addComponent(DepenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(304, Short.MAX_VALUE)))
          );
          DependenciaLayout.setVerticalGroup(
               DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(DependenciaLayout.createSequentialGroup()
                    .addContainerGap(89, Short.MAX_VALUE)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(CveDepen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addComponent(jLabel8)
                    .addGap(18, 18, 18)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(OpcDepen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(RegistrarDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(73, 73, 73))
               .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DependenciaLayout.createSequentialGroup()
                         .addGap(144, 144, 144)
                         .addComponent(DepenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(199, Short.MAX_VALUE)))
          );

          Fondo.add(Dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

          jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
          jLabel6.setText("-DEPENDENCIAS-");
          Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

          getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

          pack();
          setLocationRelativeTo(null);
     }// </editor-fold>//GEN-END:initComponents

     private void CveDepenKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveDepenKeyTyped
     {//GEN-HEADEREND:event_CveDepenKeyTyped
          Validaciones.validaAlfabeticos(evt, 15, DepenTxt.getText());
     }//GEN-LAST:event_CveDepenKeyTyped

     private void RegistrarDepBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarDepBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarDepBtnActionPerformed
          String clave = CveDepen.getText();
          String nombre = DepenTxt.getText();
          String tipo = (String) OpcDepen.getSelectedItem();
          if (clave.isEmpty() || nombre.isEmpty() || tipo.equals("-Opciones-"))
          {
               javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos",
                       "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
               return;
          }
          Dependencia nuevaDependencia = new Dependencia(tipo, clave);
          CveDepen.setText(nuevaDependencia.getClaveD());
          this.nodoDependencia = new NodoML<>(nuevaDependencia, clave);

     }//GEN-LAST:event_RegistrarDepBtnActionPerformed

     public JButton getRegistrarDepBtn()
     {
          return RegistrarDepBtn;
     }

     public NodoML getNodoDependencia()
     {
          return this.nodoDependencia;
     }

     private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
     {//GEN-HEADEREND:event_CancelarActionPerformed
          CtrlInterfaz.limpia(CveDepen);
          CtrlInterfaz.limpia(DepenTxt);
          CtrlInterfaz.limpia(OpcDepen);
     }//GEN-LAST:event_CancelarActionPerformed

     private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegresarBtnActionPerformed
     {//GEN-HEADEREND:event_RegresarBtnActionPerformed
          VtnGeneral general = new VtnGeneral();
          general.setVisible(true);
          this.dispose();
     }//GEN-LAST:event_RegresarBtnActionPerformed

     private void DepenTxtKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_DepenTxtKeyTyped
     {//GEN-HEADEREND:event_DepenTxtKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_DepenTxtKeyTyped

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Windows".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(vtnDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(vtnDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(vtnDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(vtnDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    new vtnDependencia().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton Cancelar;
     private javax.swing.JTextField CveDepen;
     private javax.swing.JTextField DepenTxt;
     private javax.swing.JPanel Dependencia;
     private javax.swing.JPanel Fondo;
     private javax.swing.JComboBox<String> OpcDepen;
     private javax.swing.JButton PrincipalBtn;
     private javax.swing.JButton PrincipalBtn1;
     private javax.swing.JButton RegistrarDepBtn;
     private javax.swing.JButton RegresarBtn;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jpnLateral;
     private javax.swing.JPanel jpnLateral1;
     // End of variables declaration//GEN-END:variables
}
