package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import edd_hospital_.modelo.Especialidad;
import edd_hospital_.multi_lista.NodoML;
import interfaces.VentanaRegistrable;
import edd_hospital_.modelo.Datos;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class vtnEspecialidad extends javax.swing.JDialog implements VentanaRegistrable
{

     private NodoML nodoEspecialidad;

     /**
      * Creates new form vtnEspecialidad
      *
      * @param parent
      * @param modal
      */
     public vtnEspecialidad(java.awt.Frame parent, boolean modal)
     {
          super(parent, modal);
          initComponents();
          CveEspecialidad.setText(String.format("E%03d", Datos.getNumeroDeRegistros() + 1));
          this.setVisible(true);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jPanel1 = new javax.swing.JPanel();
          jPanel2 = new javax.swing.JPanel();
          jPanel3 = new javax.swing.JPanel();
          RegresarBtn = new javax.swing.JButton();
          Especialidad = new javax.swing.JPanel();
          CveEspecialidad = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          RegistrarEspBtn = new javax.swing.JButton();
          jLabel4 = new javax.swing.JLabel();
          jLabel15 = new javax.swing.JLabel();
          NCamas = new javax.swing.JTextField();
          NMedicos = new javax.swing.JTextField();
          CancelarBtn = new javax.swing.JButton();
          jLabel6 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jPanel2.setBackground(new java.awt.Color(153, 153, 255));
          jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel3.setBackground(new java.awt.Color(102, 204, 255));

          RegresarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
          RegresarBtn.setText("Regresar");
          RegresarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegresarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegresarBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 152, Short.MAX_VALUE)
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                         .addGap(15, 15, 15)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(15, Short.MAX_VALUE)))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 450, Short.MAX_VALUE)
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                         .addGap(204, 204, 204)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(205, Short.MAX_VALUE)))
          );

          jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

          Especialidad.setBackground(new java.awt.Color(255, 255, 255));

          CveEspecialidad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          CveEspecialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          CveEspecialidad.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    CveEspecialidadKeyTyped(evt);
               }
          });

          jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel3.setText("Cve:");

          RegistrarEspBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarEspBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
          RegistrarEspBtn.setText("Registrar");
          RegistrarEspBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarEspBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarEspBtnActionPerformed(evt);
               }
          });

          jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel4.setText("Número de medicos: ");

          jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel15.setText("Número de camas: ");

          NCamas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NCamas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NCamas.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NCamasKeyTyped(evt);
               }
          });

          NMedicos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NMedicos.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NMedicosKeyTyped(evt);
               }
          });

          CancelarBtn.setBackground(new java.awt.Color(153, 204, 255));
          CancelarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
          CancelarBtn.setText("Cancelar");
          CancelarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CancelarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CancelarBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout EspecialidadLayout = new javax.swing.GroupLayout(Especialidad);
          Especialidad.setLayout(EspecialidadLayout);
          EspecialidadLayout.setHorizontalGroup(
               EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(EspecialidadLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel4)
                         .addComponent(jLabel15)
                         .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addComponent(CveEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                              .addGap(143, 143, 143))
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addComponent(NCamas, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                              .addGap(143, 143, 143))
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addComponent(NMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                              .addGap(152, 152, 152))))
               .addGroup(EspecialidadLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(RegistrarEspBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(223, 223, 223)
                    .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
          );
          EspecialidadLayout.setVerticalGroup(
               EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(EspecialidadLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(CveEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel15)
                         .addComponent(NCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(NMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addGap(60, 60, 60)
                              .addComponent(RegistrarEspBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(EspecialidadLayout.createSequentialGroup()
                              .addGap(71, 71, 71)
                              .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(189, 189, 189))
          );

          jPanel2.add(Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

          jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
          jLabel6.setText("-ESPECIALIDADES-");
          jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE))
          );

          getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void CveEspecialidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveEspecialidadKeyTyped
     {//GEN-HEADEREND:event_CveEspecialidadKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_CveEspecialidadKeyTyped

     private void RegistrarEspBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarEspBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarEspBtnActionPerformed
          try
          {
               if (CveEspecialidad.getText().isEmpty() || NCamas.getText().isEmpty() || NMedicos.getText().isEmpty())
               {
                    JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
               }

               int camas = Integer.parseInt(NCamas.getText());
               int medicos = Integer.parseInt(NMedicos.getText());
               String nombre = CveEspecialidad.getText();

               if (camas < 0 || medicos < 0)
               {
                    JOptionPane.showMessageDialog(this, "El número de camas y médicos no puede ser negativo", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
               }

               Especialidad especialidad = new Especialidad(camas, medicos, nombre);

               nodoEspecialidad = new NodoML(especialidad, nombre);

               JOptionPane.showMessageDialog(this, "Especialidad registrada con éxito\nClave: "
                       + especialidad.getClaveE(), "Éxito", JOptionPane.INFORMATION_MESSAGE);

          } catch (NumberFormatException ex)
          {
               JOptionPane.showMessageDialog(this, "Los campos de camas y médicos deben ser números válidos", "Error", JOptionPane.ERROR_MESSAGE);
          } catch (IllegalArgumentException ex)
          {
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
          }
     }//GEN-LAST:event_RegistrarEspBtnActionPerformed

     @Override
     public NodoML getNodoRegistrado()
     {
          return this.nodoEspecialidad;
     }
     private void NCamasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NCamasKeyTyped
     {//GEN-HEADEREND:event_NCamasKeyTyped
          Validaciones.validaEntero(evt, 2, NCamas.getText());
     }//GEN-LAST:event_NCamasKeyTyped

     private void NMedicosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NMedicosKeyTyped
     {//GEN-HEADEREND:event_NMedicosKeyTyped
          Validaciones.validaEntero(evt, 2, NMedicos.getText());
     }//GEN-LAST:event_NMedicosKeyTyped

     private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarBtnActionPerformed
     {//GEN-HEADEREND:event_CancelarBtnActionPerformed
          CtrlInterfaz.limpia(NCamas);
          CtrlInterfaz.limpia(CveEspecialidad);
          CtrlInterfaz.limpia(NMedicos);
     }//GEN-LAST:event_CancelarBtnActionPerformed

     private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegresarBtnActionPerformed
     {//GEN-HEADEREND:event_RegresarBtnActionPerformed

     }//GEN-LAST:event_RegresarBtnActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Nimbus".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(vtnEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(vtnEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(vtnEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(vtnEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    vtnEspecialidad vtn = new vtnEspecialidad(null, true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton CancelarBtn;
     private javax.swing.JTextField CveEspecialidad;
     private javax.swing.JPanel Especialidad;
     private javax.swing.JTextField NCamas;
     private javax.swing.JTextField NMedicos;
     private javax.swing.JButton RegistrarEspBtn;
     private javax.swing.JButton RegresarBtn;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     // End of variables declaration//GEN-END:variables

     @Override
     public JButton getBotonAceptarRegistro()
     {
          return RegistrarEspBtn;
     }
}
