/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edd_hospital_.vista;

import interfaces.MostrableEnTabla;
import edd_hospital_.multi_lista.NodoML;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author saulo
 */
public class VtnGeneral2 extends javax.swing.JFrame
{

    DefaultTableModel modeloTabla = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int row, int column)
        {
            return false; // ninguna celda editable
        }
    };

    public VtnGeneral2()
    {

        initComponents();

    }

    public void actualizarPanelNavegacion(List<String> ruta)
    {
        panelNavegacion.removeAll(); // Limpiar el panel antes de actualizarlo
        for (int i = 0; i < ruta.size(); i++)
        {
            String s = ruta.get(i);
            JLabel ubicacion = new JLabel(s);
            ubicacion.setFont(new Font("Arial", Font.PLAIN, 14));
            panelNavegacion.add(ubicacion);
            // Si no es el último elemento, agregar flecha
            try
            {
                if (i < ruta.size() - 1)
                {
                    JLabel flecha = new JLabel(new ImageIcon(getClass().getResource("/edd_hospital_/vista/imagenes/flecha.png")));
                    panelNavegacion.add(flecha);
                }
            } catch (Exception e)
            {
                JLabel flecha = new JLabel(">");
                panelNavegacion.add(flecha);
                System.out.println(e.getMessage());
            }
        }
        panelNavegacion.revalidate(); // Actualiza la interfaz
        panelNavegacion.repaint();    // Repinta el panel para mostrar los cambios
    }

    public void mostrarEnLaTabla(MostrableEnTabla modelProvider, NodoML raiz)
    {
        if (modelProvider == null)
        {
            return;
        }
        resetearModeloTabla();
        for (String cabecera : modelProvider.getNombreCabeceras())
        {
            modeloTabla.addColumn(cabecera);
        }
        if (raiz != null)
        {
            for (Object fila[] : modelProvider.getDatos(raiz))
            {
                modeloTabla.addRow(fila);
            }
        }
        jtbTabla.setModel(modeloTabla);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void resetearModeloTabla()
    {
        modeloTabla.setColumnCount(0);
        modeloTabla.setRowCount(0);
    }

    public JButton getBtnVolver()
    {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver)
    {
        this.btnVolver = btnVolver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jpnLateral = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jpnBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jpnSuperior = new javax.swing.JPanel();
        panelNavegacion = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 530));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jpnLateral.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jpnLateralLayout = new javax.swing.GroupLayout(jpnLateral);
        jpnLateral.setLayout(jpnLateralLayout);
        jpnLateralLayout.setHorizontalGroup(
            jpnLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jpnLateralLayout.setVerticalGroup(
            jpnLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jPanel1.add(jpnLateral, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 102, 204));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNuevoActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");

        jButton3.setText("Modificar");

        jButton4.setText("Abir");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnBotonesLayout = new javax.swing.GroupLayout(jpnBotones);
        jpnBotones.setLayout(jpnBotonesLayout);
        jpnBotonesLayout.setHorizontalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotonesLayout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addGap(45, 45, 45)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jpnBotonesLayout.setVerticalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotonesLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jpnBotones, java.awt.BorderLayout.PAGE_END);

        jpnSuperior.setBackground(new java.awt.Color(153, 153, 255));

        panelNavegacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 15));

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("TIPO_NIVEL");
        lblTitulo.setToolTipText("");

        javax.swing.GroupLayout jpnSuperiorLayout = new javax.swing.GroupLayout(jpnSuperior);
        jpnSuperior.setLayout(jpnSuperiorLayout);
        jpnSuperiorLayout.setHorizontalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSuperiorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnSuperiorLayout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(233, 233, 233)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jpnSuperiorLayout.setVerticalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSuperiorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.add(jpnSuperior, java.awt.BorderLayout.PAGE_START);

        jtbTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jtbTabla.setDragEnabled(true);
        jtbTabla.setRequestFocusEnabled(false);
        jtbTabla.setRowHeight(25);
        jtbTabla.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jtbTabla.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jtbTablaMouseClicked(evt);
            }
        });
        jtbTabla.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtbTablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTabla);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTablaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtbTablaKeyPressed
    {//GEN-HEADEREND:event_jtbTablaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbTablaKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNuevoActionPerformed
    {//GEN-HEADEREND:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnNuevoActionPerformed

    public JButton getBtnNuevo()
    {
        return btnNuevo;
    }

    public void setBtnNuevo(JButton btnNuevo)
    {
        this.btnNuevo = btnNuevo;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtbTablaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jtbTablaMouseClicked
    {//GEN-HEADEREND:event_jtbTablaMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jtbTablaMouseClicked

    public JLabel getLblTitulo()
    {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo)
    {
        this.lblTitulo = lblTitulo;
    }

    public JTable getJtbTabla()
    {
        return jtbTabla;
    }

    public void setJtbTabla(JTable jtbTabla)
    {
        this.jtbTabla = jtbTabla;
    }

    public boolean esDobleClickIzquierdo(MouseEvent evt)
    {
        return evt.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(evt);
    }

    public String getClaveSeleccionado()
    {
        String claveSeleccionado = null;
        int filaSeleccionada = jtbTabla.getSelectedRow();
        int columna = 0;
        if (filaSeleccionada != -1)
        {
            Object valor = jtbTabla.getValueAt(filaSeleccionada, columna);
            claveSeleccionado = (String) valor;
        }
        return claveSeleccionado;
    }
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVolverActionPerformed
    {//GEN-HEADEREND:event_btnVolverActionPerformed


    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnGeneral2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new VtnGeneral2().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnBotones;
    private javax.swing.JPanel jpnLateral;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JTable jtbTabla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelNavegacion;
    // End of variables declaration//GEN-END:variables
}
