package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import edd_hospital_.modelo.Datos;
import edd_hospital_.modelo.Hospitales;
import edd_hospital_.multi_lista.NodoML;
import interfaces.VentanaRegistrable;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class vtnHospitales extends javax.swing.JDialog implements VentanaRegistrable
{

     private NodoML nodoHospital;

     /**
      * Creates new form vtnHospitales
      *
      * @param parent
      * @param modal
      */
     public vtnHospitales(java.awt.Frame parent, boolean modal)
     {
          super(parent, modal);
          initComponents();
          CveHospital.setText(String.format("H%03d", Datos.getNumeroDeRegistros()));
          this.setVisible(true);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          Fondo = new javax.swing.JPanel();
          jPanel1 = new javax.swing.JPanel();
          RegresarBtn = new javax.swing.JButton();
          Hospital = new javax.swing.JPanel();
          jLabel6 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          CveHospital = new javax.swing.JTextField();
          DHospital = new javax.swing.JTextField();
          jLabel14 = new javax.swing.JLabel();
          RegistrarHospBtn = new javax.swing.JButton();
          Cancelar = new javax.swing.JButton();
          OpcNivel = new javax.swing.JComboBox<>();
          jLabel7 = new javax.swing.JLabel();

          Fondo.setBackground(new java.awt.Color(153, 153, 255));
          Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(102, 204, 255));

          RegresarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
          RegresarBtn.setText("Regresar");
          RegresarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegresarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegresarBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 152, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(15, 15, 15)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(15, Short.MAX_VALUE)))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 450, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(204, 204, 204)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(205, Short.MAX_VALUE)))
          );

          Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

          Hospital.setBackground(new java.awt.Color(255, 255, 255));

          jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel6.setText("Cve:");

          jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel8.setText("Dirección:");

          CveHospital.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          CveHospital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          CveHospital.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    CveHospitalKeyTyped(evt);
               }
          });

          DHospital.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          DHospital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          DHospital.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    DHospitalKeyTyped(evt);
               }
          });

          jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel14.setText("Nivel:");

          RegistrarHospBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarHospBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarHospBtn.setText("Registrar");
          RegistrarHospBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarHospBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarHospBtnActionPerformed(evt);
               }
          });

          Cancelar.setBackground(new java.awt.Color(153, 204, 255));
          Cancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          Cancelar.setText("Cancelar");
          Cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          Cancelar.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CancelarActionPerformed(evt);
               }
          });

          OpcNivel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          OpcNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "1", "2", "3" }));
          OpcNivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          javax.swing.GroupLayout HospitalLayout = new javax.swing.GroupLayout(Hospital);
          Hospital.setLayout(HospitalLayout);
          HospitalLayout.setHorizontalGroup(
               HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(HospitalLayout.createSequentialGroup()
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(HospitalLayout.createSequentialGroup()
                              .addGap(29, 29, 29)
                              .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel14)
                                   .addComponent(jLabel6))
                              .addGap(31, 31, 31))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospitalLayout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(RegistrarHospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel8))
                              .addGap(18, 18, 18)))
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(CveHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                         .addComponent(DHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                         .addGroup(HospitalLayout.createSequentialGroup()
                              .addGap(31, 31, 31)
                              .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(OpcNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(357, Short.MAX_VALUE))
          );
          HospitalLayout.setVerticalGroup(
               HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(HospitalLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel6)
                         .addComponent(CveHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel14)
                         .addComponent(OpcNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(DHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel8))
                    .addGap(57, 57, 57)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(RegistrarHospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(116, Short.MAX_VALUE))
          );

          Fondo.add(Hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 750, -1));

          jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
          jLabel7.setText("-Hospitales-");
          Fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void CveHospitalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveHospitalKeyTyped
     {//GEN-HEADEREND:event_CveHospitalKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_CveHospitalKeyTyped

     private void DHospitalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_DHospitalKeyTyped
     {//GEN-HEADEREND:event_DHospitalKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_DHospitalKeyTyped

     private void RegistrarHospBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarHospBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarHospBtnActionPerformed
          try
          {
               String nombre = CveHospital.getText();
               String nivelStr = (String) OpcNivel.getSelectedItem();
               String direccion = DHospital.getText();

               if (nombre.isEmpty() || nivelStr.isEmpty() || direccion.isEmpty())
               {
                    JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
               }

               int nivel;
               try
               {
                    nivel = Integer.parseInt(nivelStr);
               } catch (NumberFormatException e)
               {
                    JOptionPane.showMessageDialog(this, "El nivel debe ser un número entero",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
               }

               Hospitales nuevoHospital = new Hospitales(direccion, nivel, nombre);

               this.nodoHospital = new NodoML<>(nuevoHospital, nuevoHospital.getClaveH());

               JOptionPane.showMessageDialog(this, "Hospital registrado con éxito\nClave: "
                       + nuevoHospital.getClaveH(), "Éxito", JOptionPane.INFORMATION_MESSAGE);

          } catch (Exception ex)
          {
               JOptionPane.showMessageDialog(this, "Error al registrar el hospital: " + ex.getMessage(),
                       "Error", JOptionPane.ERROR_MESSAGE);
          }
     }//GEN-LAST:event_RegistrarHospBtnActionPerformed

     @Override
     public NodoML getNodoRegistrado()
     {
          return this.nodoHospital;
     }

     @Override
     public JButton getBotonAceptarRegistro()
     {
          return RegistrarHospBtn;
     }

     private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
     {//GEN-HEADEREND:event_CancelarActionPerformed
          CtrlInterfaz.limpia(DHospital);
          CtrlInterfaz.limpia(CveHospital);
          CtrlInterfaz.limpia(OpcNivel);
     }//GEN-LAST:event_CancelarActionPerformed

     private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegresarBtnActionPerformed
     {//GEN-HEADEREND:event_RegresarBtnActionPerformed

     }//GEN-LAST:event_RegresarBtnActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Nimbus".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(vtnHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(vtnHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(vtnHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(vtnHospitales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    vtnHospitales vtn = new vtnHospitales(null, true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton Cancelar;
     private javax.swing.JTextField CveHospital;
     private javax.swing.JTextField DHospital;
     private javax.swing.JPanel Fondo;
     private javax.swing.JPanel Hospital;
     private javax.swing.JComboBox<String> OpcNivel;
     private javax.swing.JButton RegistrarHospBtn;
     private javax.swing.JButton RegresarBtn;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JPanel jPanel1;
     // End of variables declaration//GEN-END:variables

}
