package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import edd_hospital_.modelo.Paciente;
import edd_hospital_.multi_lista.NodoML;
import edd_hospital_.modelo.Datos;
import interfaces.VentanaRegistrable;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class vtnPacientes extends javax.swing.JDialog implements VentanaRegistrable
{

     private NodoML nodoPaciente;

     /**
      * Creates new form vtnPacientes
      *
      * @param parent
      * @param modal
      */
     public vtnPacientes(java.awt.Frame parent, boolean modal)
     {
          super(parent, modal);
          initComponents();
          CveTxt.setText(String.format("P%03d", Datos.getNumeroDeRegistros() + 1));
          this.setVisible(true);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          Fondo = new javax.swing.JPanel();
          jPanel1 = new javax.swing.JPanel();
          RegresarBtn = new javax.swing.JButton();
          Paciente = new javax.swing.JPanel();
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          jLabel11 = new javax.swing.JLabel();
          jLabel12 = new javax.swing.JLabel();
          VigenciaTxt = new javax.swing.JTextField();
          NPaciente = new javax.swing.JTextField();
          RegistrarBtn = new javax.swing.JButton();
          jLabel13 = new javax.swing.JLabel();
          CveTxt = new javax.swing.JTextField();
          Cancelar = new javax.swing.JButton();
          OpcStatus = new javax.swing.JComboBox<>();
          OpcSexo = new javax.swing.JComboBox<>();
          jLabel6 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          Fondo.setBackground(new java.awt.Color(153, 153, 255));
          Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(102, 204, 255));

          RegresarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
          RegresarBtn.setText("Regresar");
          RegresarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegresarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegresarBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 152, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(15, 15, 15)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(15, Short.MAX_VALUE)))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 450, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(204, 204, 204)
                         .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(205, Short.MAX_VALUE)))
          );

          Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

          Paciente.setBackground(new java.awt.Color(255, 255, 255));

          jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel9.setText("Nombre:");

          jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel10.setText("Estatus:");

          jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel11.setText("Vigencia:");

          jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel12.setText("Sexo:");

          VigenciaTxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          VigenciaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          VigenciaTxt.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    VigenciaTxtKeyTyped(evt);
               }
          });

          NPaciente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          NPaciente.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NPacienteKeyTyped(evt);
               }
          });

          RegistrarBtn.setBackground(new java.awt.Color(153, 204, 255));
          RegistrarBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RegistrarBtn.setText("Registrar");
          RegistrarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RegistrarBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RegistrarBtnActionPerformed(evt);
               }
          });

          jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel13.setText("CVE:");

          CveTxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          CveTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          CveTxt.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    CveTxtKeyTyped(evt);
               }
          });

          Cancelar.setBackground(new java.awt.Color(153, 204, 255));
          Cancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          Cancelar.setText("Cancelar");
          Cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          Cancelar.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CancelarActionPerformed(evt);
               }
          });

          OpcStatus.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          OpcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Activo", "Inactivo", " " }));
          OpcStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          OpcSexo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          OpcSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Masculino", "Femenino", " " }));
          OpcSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          javax.swing.GroupLayout PacienteLayout = new javax.swing.GroupLayout(Paciente);
          Paciente.setLayout(PacienteLayout);
          PacienteLayout.setHorizontalGroup(
               PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(PacienteLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(39, 39, 39)
                              .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addContainerGap())
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PacienteLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18))
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(NPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                   .addComponent(OpcSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGap(27, 27, 27)
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel13)
                                             .addComponent(jLabel11))))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(VigenciaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                             .addComponent(CveTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(120, 120, 120))
                                   .addGroup(PacienteLayout.createSequentialGroup()
                                        .addComponent(OpcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
          );
          PacienteLayout.setVerticalGroup(
               PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(PacienteLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel9)
                         .addComponent(NPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel10)
                         .addComponent(OpcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel11)
                                   .addComponent(jLabel12)
                                   .addComponent(OpcSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 28, Short.MAX_VALUE)
                              .addComponent(jLabel13))
                         .addGroup(PacienteLayout.createSequentialGroup()
                              .addComponent(VigenciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(CveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(32, 32, 32)
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(114, Short.MAX_VALUE))
          );

          Fondo.add(Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

          jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
          jLabel6.setText("-PACIENTES-");
          Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void VigenciaTxtKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_VigenciaTxtKeyTyped
     {//GEN-HEADEREND:event_VigenciaTxtKeyTyped

     }//GEN-LAST:event_VigenciaTxtKeyTyped

     private void NPacienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NPacienteKeyTyped
     {//GEN-HEADEREND:event_NPacienteKeyTyped
          Validaciones.validaAlfabeticos(evt, 20, NPaciente.getText());
     }//GEN-LAST:event_NPacienteKeyTyped

     private void RegistrarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistrarBtnActionPerformed
     {//GEN-HEADEREND:event_RegistrarBtnActionPerformed
          try
          {
               String nombre = NPaciente.getText();
               String estatus = OpcStatus.getSelectedItem().toString();
               String vigencia = VigenciaTxt.getText();
               char sexo = (char) OpcSexo.getSelectedItem();
               if (nombre.isEmpty() || vigencia.isEmpty())
               {
                    JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
               }

               if (!vigencia.matches("\\d{2}/\\d{2}/\\d{4}"))
               {
                    JOptionPane.showMessageDialog(this, "Formato de vigencia inválido. Use DD/MM/AAAA",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
               }

               Paciente nuevoPaciente = new Paciente(estatus, vigencia, sexo, nombre);

               //this.nodoDependencia = new NodoML<>(nuevaDependencia, nuevaDependencia.getClaveD());
               this.nodoPaciente = new NodoML<>(nuevoPaciente, nuevoPaciente.getClaveP());
               JOptionPane.showMessageDialog(this, "Paciente registrado con éxito\nClave: "
                       + nuevoPaciente.getClaveP(), "Éxito", JOptionPane.INFORMATION_MESSAGE);

          } catch (Exception ex)
          {
               JOptionPane.showMessageDialog(this, "Error al registrar el paciente: " + ex.getMessage(),
                       "Error", JOptionPane.ERROR_MESSAGE);

          }
     }//GEN-LAST:event_RegistrarBtnActionPerformed

     private void CveTxtKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveTxtKeyTyped
     {//GEN-HEADEREND:event_CveTxtKeyTyped
          Validaciones.validaAlfanumerico(evt, 4, CveTxt.getText());
          CtrlInterfaz.habilita(rootPaneCheckingEnabled, RegistrarBtn);

     }//GEN-LAST:event_CveTxtKeyTyped

     private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
     {//GEN-HEADEREND:event_CancelarActionPerformed
          CtrlInterfaz.limpia(CveTxt);
          CtrlInterfaz.limpia(NPaciente);
          
          CtrlInterfaz.limpia(OpcStatus);
          CtrlInterfaz.limpia(VigenciaTxt);
     }//GEN-LAST:event_CancelarActionPerformed

     private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegresarBtnActionPerformed
     {//GEN-HEADEREND:event_RegresarBtnActionPerformed

     }//GEN-LAST:event_RegresarBtnActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Nimbus".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(vtnPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(vtnPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(vtnPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(vtnPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    vtnPacientes vtn = new vtnPacientes(null, true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton Cancelar;
     private javax.swing.JTextField CveTxt;
     private javax.swing.JPanel Fondo;
     private javax.swing.JTextField NPaciente;
     private javax.swing.JComboBox<String> OpcSexo;
     private javax.swing.JComboBox<String> OpcStatus;
     private javax.swing.JPanel Paciente;
     private javax.swing.JButton RegistrarBtn;
     private javax.swing.JButton RegresarBtn;
     private javax.swing.JTextField VigenciaTxt;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     // End of variables declaration//GEN-END:variables

     @Override
     public NodoML getNodoRegistrado()
     {
          return nodoPaciente;
     }

     @Override
     public JButton getBotonAceptarRegistro()
     {
          return RegistrarBtn;
     }
}
